services:
  bitwarden-mxroute-server:
    container_name: bitwarden-mxroute-server
    image: ghcr.io/deadbranches-agent/bitwarden-mxroute-server:latest
    ports:
      - "6123:6123"
    env_file: .env.example
